blog/urls.py
from django.urls import path
from . import views
from .feed import LatestPostsFeed


app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('add/', views.AddPost, name='addpost'),
    path('<int:post_id>/delete/',views.delpost, name='post_delete'),
    path('<int:post_id>/update/',views.update_post, name='post_update'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('like/', views.post_like, name='post_like'),
] 

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from blog.sitemap import PostSiteMap


sitemaps = {
    'posts': PostSiteMap,}


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blog.urls')),
    path('accounts/',include('accounts.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},name='django.contrib.sitemaps.views.sitemap'),
    path('social-auth/',include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager
from ckeditor.fields import RichTextField



class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')



class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250,verbose_name="Title")
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author= models.ForeignKey(User, related_name='blog_posts', on_delete=models.CASCADE,verbose_name="Author")
    body = RichTextField(verbose_name="Body")
    publish = models.DateTimeField(default=timezone.now,verbose_name="Publish")
    created = models.DateTimeField(auto_now_add=True,verbose_name="Created")
    updated = models.DateTimeField(auto_now=True,verbose_name="Updated")
    snippet = models.CharField(max_length=250,verbose_name="Snippet",)
    header = models.ImageField(blank=True,null=True,upload_to='blog/%Y/%m/%d',verbose_name="Header")
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')
    users_like=models.ManyToManyField(User,related_name='post_likes',blank=True)

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    objects=models.Manager()    
    published=PublishedManager()
    tags=TaggableManager()

    
    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.publish.year, self.publish.month, self.publish.day, self.slug])


class Comment(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE,related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)
    
    class Meta:
        ordering = ('created',)
    
    
    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

blog/forms.py
from django import forms
from .models import Post, Comment

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False,
                               widget=forms.Textarea)

class PostAddForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title','body','snippet','header','status','tags')

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name','email','body')


class SearchForm(forms.Form):
    query = forms.CharField()

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import EmailPostForm,PostAddForm,CommentForm,SearchForm
from django.core.mail import send_mail
from django.contrib.auth.decorators import login_required,user_passes_test
from django.utils.text import slugify
from django.contrib import messages
from taggit.models import Tag
from django.db.models import Count
from django.contrib.flatpages.models import FlatPage
from django.http import JsonResponse
from django.views.decorators.http import require_POST
#new try:


def post_list(request,tag_slug=None):
    object_list = Post.published.all()
    tag=None
    if tag_slug:
        tag=get_object_or_404(Tag,slug=tag_slug)
        object_list=object_list.filter(tags__in=[tag])
    
    
    paginator = Paginator(object_list,3)
    page=request.GET.get('page')
    try:
        posts=paginator.page(page)
    except PageNotAnInteger:
        posts=paginator.page(1)
    except EmptyPage:
        posts=paginator.page(paginator.num_pages)
   
    return render(request, 'blog/post/list.html', {'page':page,'posts': posts,'tag':tag})


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post,
                             status='published',
                             publish__year=year,
                             publish__month=month,
                             publish__day=day)
    comments = post.comments.filter(active=True)
    new_comment = None
    if request.method == 'POST': 
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
    else:
        comment_form = CommentForm()
    """ 
    Retriving similat post using tags
    """
    post_tag_ids=post.tags.values_list('id',flat=True)
    similar_posts=Post.published.filter(tags__in=post_tag_ids).exclude(id=post.id)
    similar_posts=similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags','-publish')[:4]
    return render(request, 'blog/post/detail.html', {'post': post,'comments': comments,'new_comment': new_comment,'comment_form': comment_form,'similar_posts':similar_posts})


def post_share(request,post_id):
    post=get_object_or_404(Post,id=post_id,status='published')
    sent=False
    if request.method=='POST':
        form=EmailPostForm(request.POST)
        if form.is_valid():
            cd=form.cleaned_data
            post_url=request.build_absolute_uri(post.get_absolute_url())
            subject='{} ({}) recommends you reading "{}"'.format(cd['name'],cd['email'],post.title)
            message='Read "{}" at {}\n\n{}\'s comments: {}'.format(post.title,post_url,cd['name'],cd['comments'])
            send_mail(subject,message,'agarwalharsh244@gmail.com',[cd['to']])
            sent=True
    else:
        form=EmailPostForm()
    return render(request,'blog/post/share.html',{'post':post,'form':form,'sent':sent})

def is_journalist(user):
    return user.is_staff or user.is_superuser




def AddPost(request):
    if request.method=='POST':
        form=PostAddForm(request.POST,request.FILES)
        if form.is_valid():
            post=form.save(commit=False)
            post.author=request.user
            post.slug=slugify(form.cleaned_data['title'])
            print(form.cleaned_data["header"])
            if is_journalist(request.user):
                post.save()
                return render(request,'blog/post/post_added.html',{'post':post})
            else:
                return render(request,'blog/post/not_allowed.html')
    else:
        form=PostAddForm()
    return render(request,'blog/post/add.html',{'form':form}) 


def delpost(request,post_id):
    post=get_object_or_404(Post,id=post_id)
    if is_journalist(request.user):
        post.delete()
        return render(request,'blog/post/post_deleted.html',{'post':post})
    else:
        return render(request,'blog/post/not_allowed.html')


def update_post(request,post_id):
    post=get_object_or_404(Post,id=post_id)
    if is_journalist(request.user):
        if request.method=='POST':
            form=PostAddForm(request.POST,instance=post,files=request.FILES)
            if form.is_valid():
                post=form.save(commit=False)
                post.author=request.user
                post.slug=slugify(form.cleaned_data['title'])
                post.save()
                return render(request,'blog/post/post_updated.html',{'post':post})
        else:
            form=PostAddForm(instance=post)
        return render(request,'blog/post/update.html',{'form':form})


@login_required
@require_POST
def post_like(request):
    """ Function used to like the post and maintain the record of it"""
    post_id=request.POST.get('id')
    action=request.POST.get('action')
    print(post_id,action)
    if post_id and action:
        try:
            post=Post.objects.get(id=post_id)
            if action=='like':
                post.users_like.add(request.user)
            else:
                post.users_like.remove(request.user)
            return JsonResponse({'status':'ok'})
        except:
            pass
    return JsonResponse({'status':'error'})

templates/blog/base.html
{% load static %}
{% load blog_tags %}
<!DOCTYPE html>
<html>
    <head>
      <title>{% block title %}{% endblock %}</title>  
	<link href="{% static 'css/style.css' %}" rel="stylesheet"> 
	<!--<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous"> 
    -->

    
</head>
       
<body>
   {% include 'blog/navigation.html' %}
<div id="content">
{% block content %}
{% endblock %}
</div>
<div id="sidebar">
<h2>{% block heading %} My blog {% endblock %}
<p> This is my blog. There are {% total_posts %} post so far in this blog.</p>
<p>
    <a href="{% url "blog:post_feed" %}" style="color:white;">Subscribe to my RSS feed</a>
   </p>
   
<h3>Latest posts</h3>
 {% show_latest_posts 3 %}
 <h3>Most commented posts</h3>
 {% get_most_commented_posts as most_commented_posts %}
 <ul>
  {% for post in most_commented_posts %}
  <li>
  <a href="{{ post.get_absolute_url }}" style="color:white;">{{ post.title }}</a>
  </li>
  {% endfor %}
 </ul>
 
</div>

<script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
<script src="{% static 'style.js' %}"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/js-cookie@2.2.1/src/js.cookie.min.js"></script>
<script>
  var csrftoken = Cookies.get('csrftoken');
  function csrfSafeMethod(method) {
    // these HTTP methods do not require CSRF protection
    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
  }
  $.ajaxSetup({
    beforeSend: function(xhr, settings) {
      if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
        xhr.setRequestHeader("X-CSRFToken", csrftoken);
      }
    }
  });

  $(document).ready(function(){
    {% block domready %}
    {% endblock %}
  });
</script>

</body>
</html>

templates/blog/footer.html
<a href="{% url 'blog:post_list' %}">Home</a>
{% with flatpage_list as pages %} 
    {% for page in pages %}
        <a href="{{ page.url }}">{{ page.title }}</a>
    {% endfor %}
    {% endwith %}

templates/blog/navigation.html
<!--<nav class="navbar navbar-custom">

    <div class="container-fluid">
		<a class="navbar-brand" href="">Blog</a>
		{% if request.user.is_authenticated %}
 <ul class="menu">
 <li {% if section == "dashboard" %}class="selected"{% endif %}>
 <a href="{% url "dashboard" %}" style="color:#fff">My dashboard</a>
 </li>
 
 </ul>
 {% endif %}
 <span class="user">
 {% if request.user.is_authenticated %}
 Hello {{ request.user.first_name }},
 <a href="{% url 'logout'  %}" style="color: #fff"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-box-arrow-left" viewBox="0 0 16 16">
    <path fill-rule="evenodd" d="M6 12.5a.5.5 0 0 0 .5.5h8a.5.5 0 0 0 .5-.5v-9a.5.5 0 0 0-.5-.5h-8a.5.5 0 0 0-.5.5v2a.5.5 0 0 1-1 0v-2A1.5 1.5 0 0 1 6.5 2h8A1.5 1.5 0 0 1 16 3.5v9a1.5 1.5 0 0 1-1.5 1.5h-8A1.5 1.5 0 0 1 5 12.5v-2a.5.5 0 0 1 1 0v2z"/>
    <path fill-rule="evenodd" d="M.146 8.354a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L1.707 7.5H10.5a.5.5 0 0 1 0 1H1.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3z"/>
  </svg>Logout</a>
 {% else %}
 <a href="{% url 'login' %}" style="color: #fff"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-box-arrow-in-right" viewBox="0 0 16 16">
    <path fill-rule="evenodd" d="M6 3.5a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v9a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-2a.5.5 0 0 0-1 0v2A1.5 1.5 0 0 0 6.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2h-8A1.5 1.5 0 0 0 5 3.5v2a.5.5 0 0 0 1 0v-2z"/>
    <path fill-rule="evenodd" d="M11.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5H1.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3z"/>
  </svg>Log-in</a>
 {% endif %}
 </span>
	</div> </nav> -->

<div id="header">
  <div class="brand">
  <a  class="brand" href="{% url 'blog:post_list' %}">Blog</a>
</div>
  {% if request.user.is_authenticated %}
 <ul class="menu">
 <li {% if section == "dashboard" %} {% endif %} style="padding:0px 10px 0px 0px;">
 <a href="{% url "dashboard" %}">My dashboard</a>
 </li>
 {% if request.user.is_staff or request.user.is_superuser %}
 <li><a href="{% url 'blog:addpost' %}"style="padding:0px 10px 0px 0px;">Add Post</a></li>
{% endif %}
</ul>
{% endif %} 
 <span class="user">
    {% if request.user.is_authenticated %}
    Hello {{ request.user.first_name }},
    <a href="{% url 'logout'  %}" style="color: #fff"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-box-arrow-left" viewBox="0 0 16 16">
       <path fill-rule="evenodd" d="M6 12.5a.5.5 0 0 0 .5.5h8a.5.5 0 0 0 .5-.5v-9a.5.5 0 0 0-.5-.5h-8a.5.5 0 0 0-.5.5v2a.5.5 0 0 1-1 0v-2A1.5 1.5 0 0 1 6.5 2h8A1.5 1.5 0 0 1 16 3.5v9a1.5 1.5 0 0 1-1.5 1.5h-8A1.5 1.5 0 0 1 5 12.5v-2a.5.5 0 0 1 1 0v2z"/>
       <path fill-rule="evenodd" d="M.146 8.354a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L1.707 7.5H10.5a.5.5 0 0 1 0 1H1.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3z"/>
     </svg>Logout</a>
    {% else %}
    <a href="{% url 'login' %}" style="color: #fff"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-box-arrow-in-right" viewBox="0 0 16 16">
       <path fill-rule="evenodd" d="M6 3.5a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v9a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-2a.5.5 0 0 0-1 0v2A1.5 1.5 0 0 0 6.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2h-8A1.5 1.5 0 0 0 5 3.5v2a.5.5 0 0 0 1 0v-2z"/>
       <path fill-rule="evenodd" d="M11.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5H1.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3z"/>
     </svg>Log-in</a>
    {% endif %}
    </span>
</div>

templates/blog/pagination.html
<div class="pagination">
<ul >
 {% if page.has_previous %}
 <li >
 <a  href="?page={{ page.previous_page_number }}">
<span >&laquo;</span>
</a>
</li>
 {% endif %}
 {% for i in page.paginator.page_range %}
	<li ><a  href="?page={{ i }}">{{ i }}</a>
</li>
{% endfor %}
 {% if page.has_next %}
 <li ><a  href="?page={{ page.next_page_number }}">&raquo;</a>
</li>
 {% endif %}

</ul>
</div>