blog/urls.py
from django.urls import path
from . import views
from .feed import LatestPostsFeed


app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('add/', views.AddPost, name='addpost'),
    path('<int:post_id>/delete/',views.delpost, name='post_delete'),
    path('<int:post_id>/update/',views.update_post, name='post_update'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('like/', views.post_like, name='post_like'),
] 

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from blog.sitemap import PostSiteMap


sitemaps = {
    'posts': PostSiteMap,}


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blog.urls')),
    path('accounts/',include('accounts.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},name='django.contrib.sitemaps.views.sitemap'),
    path('social-auth/',include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager
from ckeditor.fields import RichTextField



class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')



class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250,verbose_name="Title")
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author= models.ForeignKey(User, related_name='blog_posts', on_delete=models.CASCADE,verbose_name="Author")
    body = RichTextField(verbose_name="Body")
    publish = models.DateTimeField(default=timezone.now,verbose_name="Publish")
    created = models.DateTimeField(auto_now_add=True,verbose_name="Created")
    updated = models.DateTimeField(auto_now=True,verbose_name="Updated")
    snippet = models.CharField(max_length=250,verbose_name="Snippet",)
    header = models.ImageField(blank=True,null=True,upload_to='blog/%Y/%m/%d',verbose_name="Header")
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')
    users_like=models.ManyToManyField(User,related_name='post_likes',blank=True)

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    objects=models.Manager()    
    published=PublishedManager()
    tags=TaggableManager()

    
    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.publish.year, self.publish.month, self.publish.day, self.slug])


class Comment(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE,related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)
    
    class Meta:
        ordering = ('created',)
    
    
    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

blog/forms.py
from django import forms
from .models import Post, Comment

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False,
                               widget=forms.Textarea)

class PostAddForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title','body','snippet','header','status','tags')

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name','email','body')


class SearchForm(forms.Form):
    query = forms.CharField()

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import EmailPostForm,PostAddForm,CommentForm,SearchForm
from django.core.mail import send_mail
from django.contrib.auth.decorators import login_required,user_passes_test
from django.utils.text import slugify
from django.contrib import messages
from taggit.models import Tag
from django.db.models import Count
from django.contrib.flatpages.models import FlatPage
from django.http import JsonResponse
from django.views.decorators.http import require_POST
#new try:


def post_list(request,tag_slug=None):
    object_list = Post.published.all()
    tag=None
    if tag_slug:
        tag=get_object_or_404(Tag,slug=tag_slug)
        object_list=object_list.filter(tags__in=[tag])
    
    
    paginator = Paginator(object_list,3)
    page=request.GET.get('page')
    try:
        posts=paginator.page(page)
    except PageNotAnInteger:
        posts=paginator.page(1)
    except EmptyPage:
        posts=paginator.page(paginator.num_pages)
   
    return render(request, 'blog/post/list.html', {'page':page,'posts': posts,'tag':tag})


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post,
                             status='published',
                             publish__year=year,
                             publish__month=month,
                             publish__day=day)
    comments = post.comments.filter(active=True)
    new_comment = None
    if request.method == 'POST': 
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
    else:
        comment_form = CommentForm()
    """ 
    Retriving similat post using tags
    """
    post_tag_ids=post.tags.values_list('id',flat=True)
    similar_posts=Post.published.filter(tags__in=post_tag_ids).exclude(id=post.id)
    similar_posts=similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags','-publish')[:4]
    return render(request, 'blog/post/detail.html', {'post': post,'comments': comments,'new_comment': new_comment,'comment_form': comment_form,'similar_posts':similar_posts})


def post_share(request,post_id):
    post=get_object_or_404(Post,id=post_id,status='published')
    sent=False
    if request.method=='POST':
        form=EmailPostForm(request.POST)
        if form.is_valid():
            cd=form.cleaned_data
            post_url=request.build_absolute_uri(post.get_absolute_url())
            subject='{} ({}) recommends you reading "{}"'.format(cd['name'],cd['email'],post.title)
            message='Read "{}" at {}\n\n{}\'s comments: {}'.format(post.title,post_url,cd['name'],cd['comments'])
            send_mail(subject,message,'agarwalharsh244@gmail.com',[cd['to']])
            sent=True
    else:
        form=EmailPostForm()
    return render(request,'blog/post/share.html',{'post':post,'form':form,'sent':sent})

def is_journalist(user):
    return user.is_staff or user.is_superuser




def AddPost(request):
    if request.method=='POST':
        form=PostAddForm(request.POST,request.FILES)
        if form.is_valid():
            post=form.save(commit=False)
            post.author=request.user
            post.slug=slugify(form.cleaned_data['title'])
            print(form.cleaned_data["header"])
            if is_journalist(request.user):
                post.save()
                return render(request,'blog/post/post_added.html',{'post':post})
            else:
                return render(request,'blog/post/not_allowed.html')
    else:
        form=PostAddForm()
    return render(request,'blog/post/add.html',{'form':form}) 


def delpost(request,post_id):
    post=get_object_or_404(Post,id=post_id)
    if is_journalist(request.user):
        post.delete()
        return render(request,'blog/post/post_deleted.html',{'post':post})
    else:
        return render(request,'blog/post/not_allowed.html')


def update_post(request,post_id):
    post=get_object_or_404(Post,id=post_id)
    if is_journalist(request.user):
        if request.method=='POST':
            form=PostAddForm(request.POST,instance=post,files=request.FILES)
            if form.is_valid():
                post=form.save(commit=False)
                post.author=request.user
                post.slug=slugify(form.cleaned_data['title'])
                post.save()
                return render(request,'blog/post/post_updated.html',{'post':post})
        else:
            form=PostAddForm(instance=post)
        return render(request,'blog/post/update.html',{'form':form})


@login_required
@require_POST
def post_like(request):
    """ Function used to like the post and maintain the record of it"""
    post_id=request.POST.get('id')
    action=request.POST.get('action')
    print(post_id,action)
    if post_id and action:
        try:
            post=Post.objects.get(id=post_id)
            if action=='like':
                post.users_like.add(request.user)
            else:
                post.users_like.remove(request.user)
            return JsonResponse({'status':'ok'})
        except:
            pass
    return JsonResponse({'status':'error'})

templates/blog/post/add.html
{% extends "blog/base.html" %}
{% block title %}Create an post{% endblock %}
{% block content %}
 <h1>Create an Blog</h1>
 <p>Please, Add Post using the following form:</p>
 <form method="post" enctype="multipart/form-data">
  {{ form.media }}
 {{ form.as_p }}
 {% csrf_token %}
 <p><input type="submit" value="Create blog"></p>
 </form>
{% endblock %}

templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load blog_tags %}



{% block title %}{{ post.title }}{% endblock %}
{% block content %}
 <h1>{{ post.title }}</h1>
 <p class="date">
 Published {{ post.publish }} by {{ post.author }}
 </p>
 {% load thumbnail %}
 <a href="{{ post.header.url }}"> 
   <img src="{% thumbnail post.header 300x0 quality=100 %}" class="image-detail"  alt=post.title >
 </a>

 {{ post.body|markdown|safe }}

{% if request.user.is_staff or request.user.is_superuser %}
<a href='{% url "blog:post_delete" post.id %}'>
    <button style="background:white; padding:16px 32px; border:None; color:blue; border-radius: 8px;">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
            <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
            <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
          </svg>
          
    </button>
</a>
<a href='{% url "blog:post_update" post.id %}'>
    <button style="background:white; padding:16px 32px; border:None; color:blue; border-radius: 8px;">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
            <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
            <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
          </svg>
    </button>
</a>
{% endif %}

<!--For comment box       -->

{% for comment in comments %}
 <div class="comment">
 <p class="info">
 Comment  by {{ comment.name }}
 {{ comment.created }}
 </p>
 {{ comment.body|linebreaks }}
 </div>
{% empty %}
 <p>There are no comments yet.</p>
{% endfor %}
{% if new_comment %}
 <h2>Your comment has been added.</h2>
{% else %}
 <h2>Add a new comment</h2>
 <form method="post">
 {{ comment_form.as_p }}
 {% csrf_token %}
 <p><input type="submit" value="Add comment">

  
</form>
{% endif %}

<!--Html structure for similar posts-->
<h2> Similar Posts</h2>
{% for post in similar_posts %}
<p>
<a href="{{ post.get_absolute_url }}">
{{ post.title }}
</a>
</p>
{% empty %}
<p>There are no similar posts yet.</p>
{% endfor %}

{% endblock %}

templates/blog/post/latest_posts.html
<ul>
    {% for post in latest_posts %}
    <li>
    <a href="{{ post.get_absolute_url }}" style="color:white;">{{ post.title }}</a>
    </li>
    {% endfor %}
   </ul>

templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% load static %}



{% load static %}
{% block title %}My Blog{% endblock %}
{% block content %}
 <h1>My Blog</h1>
 {% for post in posts %}
 <h2>
 <a href="{{ post.get_absolute_url }}">
 {{ post.title }}
 
 </a>
 </h2>
 {% if post.header %}
 
 {% load thumbnail %}
 <a href="{{ post.header.url }}"> 
   <img src="{% thumbnail post.header 300x0 quality=100 %}" class="image-detail"  alt=post.title >
 </a>
{% endif %}
 <p class="tags">Tags: 
  {% for tag in post.tags.all %}
  <a href="{% url "blog:post_list_by_tag" tag.slug %}">
  {{ tag.name }}
  </a>
  {% if not forloop.last %}, {% endif %}
  {% endfor %} 
</p>
 <p class="date">
 Published {{ post.publish }} by {{ post.author }}
 </p>
 <!--Safe tag here is to just remove html tags that append from ckeditor-->
 {{ post.snippet }}
 <!--{{ post.body|markdown|truncatewords:30|safe }} -->
 <p>
    <a href='{% url "blog:post_share" post.id %}'>
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-share" viewBox="0 0 16 16">
            <path d="M13.5 1a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3zM11 2.5a2.5 2.5 0 1 1 .603 1.628l-6.718 3.12a2.499 2.499 0 0 1 0 1.504l6.718 3.12a2.5 2.5 0 1 1-.488.876l-6.718-3.12a2.5 2.5 0 1 1 0-3.256l6.718-3.12A2.5 2.5 0 0 1 11 2.5zm-8.5 4a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3zm11 5.5a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3z"/>
          </svg>
    </a>
   </p>
<!--Like button division working -->

<div>
  {% with total_likes=post.users_like.count users_like=post.users_like.all %}
  <span class="count">
  <span class="total">{{ total_likes }}</span>
  like{{ total_likes|pluralize }}
  </span>
  <a href="#" data-id="{{ post.id }}" data-action="{% if request.user in users_like %}un{% endif %}like" class="like button">
  {% if request.user not in users_like %}
  Like
  {% else %}
  Unlike
  {% endif %}
  </a>
  </div>
{% endwith %}



{% endfor %}
 {% include "blog/pagination.html" with page=posts %}
 {% if tag %}
 <h2>Posts tagged with "{{ tag.name }}"</h2>
{% endif %}

{% endblock %}









{% block domready %}
  $('a.like').click(function(e){
    e.preventDefault();
    $.post('{% url "blog:post_like" %}',
      {
        id: $(this).data('id'),
        action: $(this).data('action')
      },
      function(data){
        if (data['status'] == 'ok')
        {
          var previous_action = $('a.like').data('action');

          // toggle data-action
          $('a.like').data('action', previous_action == 'like' ?
          'unlike' : 'like');
          // toggle link text
          $('a.like').text(previous_action == 'like' ? 'Unlike' :
          'Like');

          // update total likes
          var previous_likes = parseInt($('span.count .total').text());
          $('span.count .total').text(previous_action == 'like' ?
          previous_likes + 1 : previous_likes - 1);
        }
      }
    );
  });
{% endblock %}

templates/blog/post/not_allowed.html
{% extends "blog/base.html" %}

{% block content %}
You are not authorized to create blog please contact the administrator. <a href="{% url 'blog:post_list' %}">main page</a>

{% endblock %}

templates/blog/post/pagination.html
<div class="pagination">
 <span class="step-links">
 {% if page.has_previous %}
 <a href="?page={{ page.previous_page_number }}">Previous</a>
 {% endif %}
 <span class="current">
 Page {{ page.number }} of {{ page.paginator.num_pages }}.
 </span>
 {% if page.has_next %}
 <a href="?page={{ page.next_page_number }}">Next</a>
 {% endif %}
 </span>
</div>

templates/blog/post/post_added.html
{% extends "blog/base.html" %}
{% block title %}Welcome{% endblock %}
{% block content %}
 <h1>Welcome {{ new_user.first_name }}!</h1>
 <p>Your blog has been successfully added!</p>
{% endblock %}

templates/blog/post/post_deleted.html
{% extends "blog/base.html" %}
    
    {% block content %}
        <h1>You had successfull deleted {{ post.title }}.</h1>
        <a href="{% url 'blog:post_list' %}">main page</a>
    {% endblock %}

templates/blog/post/post_updated.html
{% extends "blog/base.html" %}
    
    {% block content %}
        <h1>You had successfull updated {{ post.title }}.</h1>
        <a href="{% url 'blog:post_list' %}">main page</a>
    {% endblock %}

templates/blog/post/share.html
{% extends "blog/base.html" %}

{% block title %}Share a post{% endblock %}
{% block content %}
 {% if sent %}
 <h1>E-mail successfully sent</h1>
 <p>
 "{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.
 </p>
 {% else %}
 <h1>Share "{{ post.title }}" by e-mail</h1>
 <form method="post">
 {{ form.as_p }}
 {% csrf_token %}
 <input type="submit" value="Send e-mail">
 </form>
 {% endif %}
{% endblock %}

templates/blog/post/update.html
{% extends "blog/base.html" %}

{% block title %}Update post{% endblock %}

{% block content %}
<h1>Create an Blog</h1>
<p>Please, Add Post using the following form:</p>
<form method="post" enctype="multipart/form-data">
{{ form.media }}
{{ form.as_p }}
{% csrf_token %}
<p><input type="submit" value="Update blog"></p>
</form>
{% endblock %}